deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: TFlB/tuXSHK//Ibq3VPMQhHRVVFTnKBYTu+10RXpGDTOzJwapFP/y7e6aF3U8A8e/M8JAgkbvJ3pDfCQHW65gGxLLKnurtodbQ3aSKxB242v0xnTjSptdEgWWwHxJSDMTR9ESCzUMgIDhUJJddnyutMVqBjpAJ+tNB6ZHeVI8Zx4UEZ7K8P+QnQVMOz+UyXYYebtbzmaLG0p6rKTViwboEeegs6JyRFBaeneaFvqt74P6cn0y7o/1GIqkkmxC/pxdBTrjcAUNrP+MyfZRuuRjkpm/zR4OYK5jNJVFXL6xjv6Qn7ipHZngmcwzthh5C3RQ8sDsYeNX5Ygh3MQRtm8237DBXkOPtTkRjjYkTimUz7k2yb18TNQXzoe5QQEJDjeLnKWaU6ToBnwhjFgqgZ5UnMBzD015PgmmHKFqlNdfCW9T/ZxoI4BFUuAYCVYwy050Z1k4T3UJK9wbnuyAcdtPwFlVna5j0FYoveh6agpPJCA2RbowYkWhsG948uD/7Ah0KGZgYrM0Y87sHSigF3M/2C4sa63r/+YfBjZyh3aGyO8DwOksFl/0PrelaLGX1wdF+gjaChV5LEXvTpfj0F6TFiMMD3A6ej6TSPW+/ucbs/ikqTDiqYRVJj72eN2hv4VSMrBiS9Qi4lLk5e5wxILqfpa1CpKXdClvjng/10DG4c=
  keep_history: true
  on:
    branch: master
